# Generated by Django 2.0.7 on 2018-07-13 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='death_of_death',
            new_name='date_of_death',
        ),
    ]
